### ISSUE TITLE
Not working in env with single EX2016 CU22 server

### ISSUE THREAD

**Issue by brolifen** [IngoGege/Get-MAPIStats#1]
Tried the script on a single EX2016 CU22 envinrement but does not seem to work. First it says there is no server found. If I hacked it by giving the server name and installation folder inside of the script it seems to find the logs but a log parser error appears "Error: Syntax Error: extra token(s) after query: 'BY'"

Would be nice if this script still works as it helps a lot with performance troubleshooting.

**Comment by IngoGege** [comment]
Looking into this now.

**Comment by IngoGege** [comment]
@brolifen I fixed the script and removed legacy code. I would appreciate having it tested on your side.
