### ISSUE TITLE
Not working on Server 2019

### ISSUE THREAD

**Issue by NytSong** [IngoGege/Get-MAPIStats#2]
Trying this on a fully up to date exchange server on windows server 2019
It just tells me that there are no servers found.

**Comment by IngoGege** [comment]
Hi,
you run it on Exchange server itself?
Ciao,
Ingo

**Comment by NytSong** [comment]
Yes, I tried it directly on the exchange server because it's wasn't working for me elsewhere.

**Comment by IngoGege** [comment]
Ok, which CU?

**Comment by NytSong** [comment]
Well, it appears our Exchange server hasn't wanted to gracefully update past Exchange 2019 CU12 Nov23SU so that's where we're at.
Also, if it makes any difference, we have it installed on a K: drive due to someone else's decisions before I came on.

**Comment by IngoGege** [comment]
Hi @NytSong ,
sorry for the delay. The script uses ADSI to query for Exchange severs. Could you check in AD attribute msexchcurrentserverroles on your Exchange server? Which number is it?
Ciao,
Ingo

**Comment by NytSong** [comment]
Going to be honest that I'm not seeing said attribute.  I'm starting to question my sanity.  I know we've been thinking about rebuilding our exchange server because in all of the upgrades and such something appears to have not been done right.  All of this was before me, the jr sys admin in the picture who is still learning.

**Comment by IngoGege** [comment]
Sorry to hear that. However, this attribute is crucial and that’s what the script is looking for to find Exchange servers.
I‘ll close this issue. Feel free to open a new one, once it’s not working with a proper Exchange setup.

**Comment by NytSong** [comment]
Well, at least you provided another hint that things are not right here.  Thanks for the patience.
